#!/usr/bin/perl -CA

# ----------------------------------------------------------------------
#
# 2023-05-03:
#  - Change schema so that seasons is a list with season -> INT as key
#  - Use YAML rather than JSON as data format
#
# 2023-02-19
#
# ----------------------------------------------------------------------

use 5.36.0;
use Encode;
use JSON::XS;
use YAML;
use Data::Dumper;
use Perl6::Slurp;
use File::Basename;
use File::Spec::Functions;

# ----------------------------------------------------------------------
#
# get_js_file
#
# ----------------------------------------------------------------------

sub get_js_file {
    my ($path) = @_;
    return decode_json(slurp($path));
}

sub get_titles_yaml {
    my ($path) = @_;
    return YAML::LoadFile($path);
}

# ----------------------------------------------------------------------
#
# mangle
#
# ----------------------------------------------------------------------

sub mangle {
    my ($t) = @_;

    # Remove special characters

    $t =~ s:[\!\$\(\)+/?.,\:'&]::g;

    # Convert spaces and hyphens to underscores

    $t =~ s:[\- ]:_:g;

    # Remove multiple _

    $t =~ s:[_]+:_:g;
    
    return $t;
}

# ----------------------------------------------------------------------
#
# rename_files
#
# ----------------------------------------------------------------------

sub rename_files {
    my ($series_list, $files) = @_;
    
# --------------------
# Build regex list
# --------------------

    my @rxlist;
    
    for my $series (@$series_list)
    {
	my $name = $series->{series};

	# --------------------
	# Have seasons
	# --------------------

	if (my $seasons = $series->{seasons})
	{
	    foreach my $season (@$seasons)
	    {
		my $number = $season->{season};
#		printf("%s [S %d]\n", $name, $number);
		my $episode = exists($season->{start}) ? $season->{start} : 1;
		foreach my $title (@{$season->{titles}})
		{
		    my $regex = sprintf("%s.%02d.%02d", mangle($name), $number, $episode);
#		    say $regex;
		    push(@rxlist, [ $regex, $name, $number, $episode, $title ]);
		    $episode++;
		}
	    }
	}
	else
	{
	    # --------------------
	    # Single season / No seaons
	    # --------------------
	    
	    my $titles = $series->{titles};
	    my $i = (exists($series->{start})) ? $series->{start} : 1;
	    printf("%s - old format\n", $name) if ($series->{season});
	    
	    for my $t (@$titles)
	    {
		my $regex;
		if (my $season = $series->{season})
		{
		    $regex = sprintf("%s.%02d.%02d", mangle($name), $season, $i);
		    push(@rxlist, [ $regex, $series, $season, $i, $t ]);
		}
		else
		{
		    $regex = sprintf("%s.%02d", mangle($name), $i);
		    push(@rxlist, [ $regex, $series, undef, $i, $t ]);
		}
		$i++;
	    }
	}
    }

# --------------------
# Match regex to list of files
# --------------------

    foreach my $path (@ARGV)
    {
	next if (! -f $path);
    
	my $src = basename($path);
	my $dir = dirname($path);

	for my $rx (@rxlist)
	{
	    if (grep(m:$rx->[0]:, $src))
	    {
		$src =~ m:\.([A-Za-z0-9]+)$:;
		my $suffix = $1;
		my $dst = sprintf("%s.%s.%s", $rx->[0], mangle($rx->[4]), $suffix);
		if ($src cmp $dst)
		{
		    $src = catfile($dir, $src);
		    $dst = catfile($dir, $dst);
		    rename($src, $dst);
		    printf("%s -> %s\n", $src, $dst);
		}
	    }
	}
    }
}


# ----------------------------------------------------------------------
#
# M A I N
#
# ----------------------------------------------------------------------

binmode(STDOUT, ":utf8");

# my $titles = get_js_file("/home/ralexand/src/titlemedia/titles.js");
my $titles = get_titles_yaml("/home/ralexand/src/titlemedia/titles.yaml");


rename_files($titles, [@ARGV]);
    
